### ISSUE TITLE
Please don't send me any notification for jsrsasign

### ISSUE THREAD

**Issue by kjur** [jsdelivr/jsdelivr#11051]
Please don't send me (@kjur) when I update my jsrsasign npm modules. I don't need any such notification. Thanks.

For example like this:
https://github.com/jsdelivr/jsdelivr/pull/11045

**Comment by jimaek** [comment]
Github provides this functionality by default. Just click the ignore button here
![firefox_2016-04-14_21-27-40](https://cloud.githubusercontent.com/assets/1834071/14540925/cc694996-0287-11e6-9f8a-f94ca3fd78c0.png)

**Comment by kjur** [comment]
I don't think so. My setting is "Not watching". I seem that automatic pull request process will include "@kjur" in the comment. That's the cause.

**Comment by jimaek** [comment]
"Not watching" means that you wont get anything unless you are mentioned. Since the bot is mentioning you to stop receiving them you need to set it to "Ignoring".
There is no way to stop mentioning per user, the easiest way is for you to simply use the "Ignoring" function of Github for this repo.
It will solve your problem

**Comment by kjur** [comment]
I got it. Thank you so much. I've set to 'Ignoring'.
