### ISSUE TITLE
New Version Syncfusion packages not updated

### ISSUE THREAD

**Issue by Syncfusion-JavaScript** [jsdelivr/jsdelivr#17325]
We have released the new version (15.1.0.41) Syncfusion-ej-global (https://www.jsdelivr.com/projects/syncfusion-ej-global) and Syncfusion-JavaScript (https://www.jsdelivr.com/projects/syncfusion-javascript) packages. But these are still not yet updated in registry.

Please look into this and update the latest version (15.1.0.41) Syncfusion packages.

Regards,
Ganesan R.

**Comment by megawac** [comment]
You should be getting notifications of the bot trying to update the versions (https://github.com/jsdelivr/jsdelivr/pull/17303). If not feel free to look through the pull requests to see if your repo has changes queued. Unfortunately your repo will always fail automatic merging due to Github limitations regarding pull requests with a lot of files.
