### ISSUE TITLE
Do not add generated comment header to already minified files.

### ISSUE THREAD

**Issue by JorgeBucaran** [jsdelivr/jsdelivr#18041]
When I tried to access https://cdn.jsdelivr.net/npm/hyperapp I got this header with the code:

```
/**
 * Skipped minification because the original files appears to be already minified.
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
```

Would you consider not adding this header by default?

Cheers!

**Comment by MartinKolarik** [comment]
The header is important because it allows you to distinguish between files provided directly in the package and those generated on our end. You can always use the direct link to get the original file: https://cdn.jsdelivr.net/npm/hyperapp@0.12.1/dist/hyperapp.js (the one that's served at the short link is https://cdn.jsdelivr.net/npm/hyperapp@0.12.1/dist/hyperapp.min.js)

**Comment by jimaek** [comment]
You can remove the message from here https://cdn.jsdelivr.net/npm/hyperapp by changing package.json and adding `jsdelivr: hyperapp.min.js`

**Comment by JorgeBucaran** [comment]
Thanks, that sounds doable! 👍

**Comment by MartinKolarik** [comment]
@jimaek there's no `hyperapp.min.js`

**Comment by JorgeBucaran** [comment]
@MartinKolarik Right, can I just link any file? 

The minified bundle is in `dist/hyperapp.js`.

**Comment by MartinKolarik** [comment]
@JorgeBucaran you'd have to rename `hyperapp.js` to `hyperapp.min.js`, then jsDelivr knows the file is already minified and won't attempt to modify it.

**Comment by JorgeBucaran** [comment]
@MartinKolarik I see. Bummer! That doesn't work for me. 

Cheers! 👋

**Comment by MartinKolarik** [comment]
In that case just use the direct link as I suggested before.
