### ISSUE TITLE
jsdelivr @latest tag not point the latest version

### ISSUE THREAD

**Issue by yujiangshui** [jsdelivr/jsdelivr#18063]
Thanks for your amazing works!

I make a test, publish a package with 1.0.0 and the content is https://cdn.jsdelivr.net/npm/jsdeliver-test@1.0.0/hello.html

And then I request the latest tag https://cdn.jsdelivr.net/npm/jsdeliver-test@latest/hello.html, it works fine.

But when I publish 1.0.1 https://cdn.jsdelivr.net/npm/jsdeliver-test@1.0.1/hello.html and change the content, the latest tag file still unchanged. It seems like jsdelivr s3 cache service treat latest tag as normal version and not update the cache?

But the latest tag in npm will point the dynamic version which user set.

**Comment by MartinKolarik** [comment]
The CDN caches the file (that's the whole point of using a CDN), which is why you don't see the new version immediately. `@latest` and all other tags may take up to 24 hours to update. There's also an API which can be used to force an immediate update. See readme for more info: https://github.com/jsdelivr/jsdelivr#purge-cache

**Comment by yujiangshui** [comment]
got it. It's a misunderstanding. thanks

**Comment by ycjcl868** [comment]
+ 1
