### ISSUE TITLE
Package not updating

### ISSUE THREAD

**Issue by samdenty99** [jsdelivr/jsdelivr#18077]
Hey there, sorry to bother! I recently published a new version to [@widgetbot/crate](https://www.jsdelivr.com/package/npm/@widgetbot/crate), but the tagged version `https://cdn.jsdelivr.net/npm/@widgetbot/crate@3` doesn't seem to reflect these changes.

I've tried using the purge API to clear it, but it's still serving a stale version. I've also noticed that the headers on that endpoint instruct the client to cache the file for 7 days (preventing new version from being downloaded without a force refresh)

Is it possible to clear this url & is there another endpoint with a shorter cache expiration time?

**Comment by MartinKolarik** [comment]
`v3.1.231` > ` 3.1.25` (when comparing as semver), which is why you are still getting `v3.1.231` (I believe it works this way in npm cli too). You'll need to either publish the latest changes as `v3.1.232` or `v3.2.0`.

As for the client cache expiration, yes - 7 days is a good balance of performance (files not downloaded too often) and relatively fast updates. If you need frequent updates/hotfixes, you can either:
 - use links with a specific version and update those every time
 - add a query string with a version to the URL - this will force new fetch on the client but won't prevent updates to newer versions (so you'd only change the query string when you really need an immediate update, otherwise the file would still get updated in 7 days)
