### ISSUE TITLE
Problem with versioning

### ISSUE THREAD

**Issue by namiltd** [jsdelivr/jsdelivr#18086]
In my project 
https://cdn.jsdelivr.net/gh/namiltd/bootstrap-ie/js/bootstrap-ie8.js is not the same as https://cdn.jsdelivr.net/gh/namiltd/bootstrap-ie@4.1.3-4/js/bootstrap-ie8.js

https://cdn.jsdelivr.net/gh/namiltd/bootstrap-ie/js/bootstrap-ie9.js is not the same as https://cdn.jsdelivr.net/gh/namiltd/bootstrap-ie@4.1.3-4/js/bootstrap-ie9.js

https://cdn.jsdelivr.net/gh/namiltd/bootstrap-ie/css/bootstrap-ie8.css is not the same as https://cdn.jsdelivr.net/gh/namiltd/bootstrap-ie@4.1.3-4/css/bootstrap-ie8.css
...
etc
Question : why ?

**Comment by MartinKolarik** [comment]
It seems you previously had a release `v4.1.302` which you deleted and replaced with `4.1.3-4` ? In that case we still consider `v4.1.302` the latest available version because only versions in `MAJOR.MINOR.PATCH` format are considered. Versions with additional metadata (`-4` in this case) are ignored. Also `4.1.3` is a lower version number than `4.1.302`.

**Comment by namiltd** [comment]
All clear. Tnx for info.
