### ISSUE TITLE
How is jsDelivr handling cookie consent?

### ISSUE THREAD

**Issue by ghost** [jsdelivr/jsdelivr#18132]
I noticed jsDelivr adds cookies when I visit but does not provide the opportunity to consent to those cookies. Under GDPR _Privacy by design_ means natural persons in the EU cannot have unique identifiers collected such as `__cfuid` (a unique identifier) and Google Analytics without first opting-in.

https://eugdpr.org/the-regulation/gdpr-faqs/

Should a cookie consent be added so users have the choice to opt-in to this personal data collection?

**Comment by SukkaW** [comment]
The cookie is added by [Cloudflare](https://www.cloudflare.com), one of CDN providers of jsDelivr. And how Cloudflare work with GDPR can be found [here](https://www.cloudflare.com/gdpr/introduction/).

**Comment by jhabdas** [comment]
Thanks, I've seen the CloudFlare internal documents. What I'm more interested in is the fact [CloudFlare is using](https://www.privacyshield.gov/participant?id=a2zt0000000GnZKAA0&status=Active) the personal identifier for marketing purposes. Because GDPR requires opt-in for personal data collection and jsDelivr uses CloudFlare a cookie with a personal identifier _should not_ be set without first gaining consent from individuals using jsDelivr.

**Comment by MartinKolarik** [comment]
I'm not 100% sure about the "should not" bit, but since the cookie is set by CF, it isn't even technically possible to require consent before it's set. Also, this only applies to the website. The CDN doesn't use any cookies.
