### ISSUE TITLE
The QUANTIL has stopped providing China PoPs for jsDelivr

### ISSUE THREAD

**Issue by SukkaW** [jsdelivr/jsdelivr#18176]
```bash
$ dig cdn.jsdelivr.net @114.114.114.114

cdn.jsdelivr.net.       33      IN      CNAME   jsdelivr.a7e454.flexbalancer.net.
jsdelivr.a7e454.flexbalancer.net. 33 IN CNAME   cdn.jsdelivr.net.mwcloudcdn.com.
cdn.jsdelivr.net.mwcloudcdn.com. 33 IN  A       14.0.44.218
cdn.jsdelivr.net.mwcloudcdn.com. 33 IN  A       14.0.43.169
```

For mainland China the DNS is pointed to `cdn.jsdelivr.net.mwcloudcdn.com`, but `14.0.44.218` is a CDNetworks (has been acquired by QUANTIL) Tokyo PoP IP, and `14.0.43.169` is a CDNetworks Osaka PoP IP.

**Comment by SukkaW** [comment]
From China MIIT, I can see the ICP license for `jsdelivr.net` is still valid. What happend?

![image](https://user-images.githubusercontent.com/40715044/64710019-d656ec00-d4e9-11e9-89e0-2cd18efc6a39.png)

**Comment by jimaek** [comment]
The ICP license is up for renewal and one of the requirements is to transfer the domain to a Chinese registrar. We don't see a safe way to do it without risking serious downtime or worse.
So Quantil is testing their near-China network, they assured us that the performance will be similar to their mainland.

**Comment by hifocus** [comment]
> The ICP license is up for renewal and one of the requirements is to transfer the domain to a Chinese registrar. We don't see a safe way to do it without risking serious downtime or worse.
> So Quantil is testing their near-China network, they assured us that the performance will be similar to their mainland.

Thanks for your answer. I am sorry if I misunderstood your words, but do you mean jsDelivr is not going to risk the possibility to have its service down while transferring domain, therefore in the future since the domain won't be transferred to a Chinnese registrar, and users in mainland China won't be able to use Quantil's mainland PoPs anymore?

In the best of my knowledge, PoPs outside of China (even in Japan) will definetely work differently, i.e. having worse experiences. If my understanding above is correct, may I suggest that jsDelivr to purchase at a Chinese registrar, or transfer a different domain into China, then service everything exactly the same as `cdn.jsdelivr.net`, and still having Quantil's China PoPs?

Thanks again for servicing jsDelivr.

**Comment by jimaek** [comment]
I believe Quantil has not yet finished the complete transfer of the service so its a bit early for performance tests. Rest assured jsDelivr's main priority is production readiness, that means best possible uptime and performance. So we will do our best to ensure good performance in China.

And no the issue is not the transfer itself which is pretty simple. The process of verification after the transfer could include the complete removal of NS records from the domain for multiple hours or even days as it happened with another company according to our partner in China. We simply can't risk the global downtime of the service for multiple hours or days.

**Comment by MartinKolarik** [comment]
@hifocus we're also getting thousands of benchmarks from all around China every hour (thanks to [PerfOps](https://perfops.net)) and we're monitoring this closely. Right now the performance is indeed worse than before but still way better than Cloudflare and as @jimaek said we believe it will improve further. We'll let you know when we have all details about the final solution.

**Comment by hifocus** [comment]
Thanks very much indeed

**Comment by SukkaW** [comment]
FYI, using multiple monitor (Run by [IPIP](https://en.ipip.net)) located in China, it can be seen that most of the requests from China will hit QUANTIL PoPs located in Tokyo, Osaka, Taipei, Xinbei City and Singapore.

![image](https://user-images.githubusercontent.com/40715044/64889049-072c5200-d69f-11e9-94ea-a7f2a02e524b.png)

**Comment by luminouskk** [comment]
The CDN recently not performance so good in China mainland these day. At midnight a .css aroud 300k will take about 6 seconds to load it. That's so bad.

Thank you for providing such strong project. But it's really not suitable for users in China mainland.

**Comment by SukkaW** [comment]
@luminouskk 

Just as jsDelivr staff @MartinKolarik said, the performance in mainland China has been monitored by jsDelivr closely:

![image](https://user-images.githubusercontent.com/40715044/65914766-93ab7400-e404-11e9-836f-4ddfcd51747e.png)

And I have contact some cloud computing company and some of them has interests in sponsoring jsDelivr with their near-china network.

**Comment by jimaek** [comment]
We are in progress of optimizing this. Its a temp solution to avoid total downtime and give us time to come up with something better.

**Comment by wusatosi** [comment]
> We are in progress of optimizing this. Its a temp solution to avoid total downtime and give us time to come up with something better.

Any follow up?

**Comment by SukkaW** [comment]
Well, I have just asked SHCA MIIT, it seems that ICP License in Shanghai dose not require domain to be registered at Chinese registrar. Since `jsdelivr.net` ICP License is validated by SHCA MIIT, It should be OK then.

**Comment by jimaek** [comment]
Just to update everyone we are still working on bringing mainland China back. Just please be patient.

**Comment by wusatosi** [comment]
> Well, I have just asked SHCA MIIT, it seems that ICP License in Shanghai dose not require domain to be registered at Chinese registrar. Since `jsdelivr.net` ICP License is validated by SHCA MIIT, it should be OK then.

sounds great !

**Comment by wusatosi** [comment]
> Just to update everyone we are still working on bringing mainland China back. Just please be patient.

Thanks for the update 😄

**Comment by jimaek** [comment]
We renewed our ICP license and enabled mainland China back! 
![jsdelivr](https://user-images.githubusercontent.com/1834071/68022619-2578fc00-fca5-11e9-932f-fa69bb0c2358.png)

I am sorry to our Chinese users for this period of low performance, but unfortunately it was necessary to avoid the risk of downtime which is unacceptable to us.

**Comment by SukkaW** [comment]
@jimaek Thanks for servicing jsDelivr! jsDelivr is awesome.

**Comment by jimaek** [comment]
We would also really appreciate some love in foreign languages. Maybe a blog post or mention on some dev communities. 
We can't do it ourselves so it would be really helpful!

**Comment by MartinKolarik** [comment]
And of course, we also appreciate mentions in English 😄
