### ISSUE TITLE
Question about project hits

### ISSUE THREAD

**Issue by rafa8626** [jsdelivr/jsdelivr#18218]
Hi, I'm the creator of OpenPlayerJS (https://github.com/openplayerjs/openplayerjs), and during this month I saw a tremendous spike on hits on my project (don't get me wrong, I'm happy to see so many new hits on it :) ).

But in the past few days the number was zero, and tonight I checked it back and it's now 7M hits. I'd like to ask how are does hits tracked, and if you could provide an insight of what could cause that spike on hits.

Such a great project!

**Comment by MartinKolarik** [comment]
Hi, there was recently an issue which caused some stats processing to be delayed, which is why you might have seen zero hits in the past few days. The numbers are up to date now and seem to be stable at 100k+ hits/day.

Given the sudden increase, it is likely that the package was included on some high traffic website but we don't store referrer <-> package relationships (yet) so don't know where exactly it's used.

**Comment by rafa8626** [comment]
Thanks @MartinKolarik for the quick response; do you have an estimate on how long would you be able to have the referrer/package relationship available? It sounds like an interesting addition to this project

**Comment by MartinKolarik** [comment]
Not sure yet but if we add it, we'll likely aim for at least 1 year as that's what we provide for all other types of stats at this point. You can subscribe to jsdelivr/data.jsdelivr.com#17 to get notified when there is any news about this.

**Comment by rafa8626** [comment]
Thanks for the update
