### ISSUE TITLE
Consider leaving TypeScript reference comments intact upon minification

### ISSUE THREAD

**Issue by Avaq** [jsdelivr/jsdelivr#18224]
I've been experimenting with using jsDelivr to distribute libraries for [Deno](https://deno.land/). I think jsDelivr is a really good fit for Deno.

I have made a library available for consumption in Deno over here: https://cdn.jsdelivr.net/gh/fluture-js/Fluture@dist2/dist/module.js

In the head of this file, you'll find the following comment:

```ts
/// <reference types="https://cdn.jsdelivr.net/gh/fluture-js/Fluture@dist2/index.d.ts" />
```

This comment tells TypeScript compilers where to find the typings for this file. It is the [documented](https://deno.land/manual/getting_started/typescript#triple-slash-reference-directive-in-javascript-files) way in Deno to annotate a JavaScript file with TypeScript typings.

jsDelivr also provides a minified version of the code automatically: https://cdn.jsdelivr.net/gh/fluture-js/Fluture@dist2/dist/module.min.js

The problem here of course is that the comment has been stripped out, which means that Deno will think all types in the minified version of the code are `any`.

----

I myself am not even sure if jsDelivr should handle this case. I could view it in two ways.

The first is to say that the comment is not like other comments. It actually has meaning: It actually is *code*, not comment, for some run-times. Stripping it out on minification is altering the behaviour of the code, which you would never want from a minification step. To illustrate this point, you can do the following experiment:

1. Create a file `test.ts` with the following contents:

    ```ts
    import * as fl from 'https://cdn.jsdelivr.net/gh/fluture-js/Fluture@dist2/dist/module.js'
    fl.alt (fl.resolve (42)) (fl.resolve ('hi'))
    ```

2. Install Deno and run the code with `deno run test.ts`
3. Observe the behaviour of the code: A compiler error is generated.
4. Change `module.js` to `module.min.js` in the import statement.
5. Run again, observe a different behaviour. The minified version behaves differently.

However, I can totally imagine that jsDelivr would say: "We deliver JavaScript, not TypeScript, and in JavaScript, a comment is a comment and not code." And that's the other way of looking at it. Maybe I should not even have brought this issue to your attention, because it might be out of scope. What do you think?

**Comment by Avaq** [comment]
Reflecting on this issue, I think there's other kinds of comment annotations that might be worth preserving:

- Purity annonations: `/*#__PURE__*/`
- Linting annotations: `//eslint-disable-next-line`, `/* global varName */`, `/* eslint underscores:0 */`
- Code coverage annotations: `//istanbul-ignore-next`

Each of these annotations might end up altering the behaviour of some runtime when they are stripped out.

So maybe the question becomes more generally whether that's something a minifier should concern itself with, to which I am personally inclined to say "no".

However, it may still be worth making an exception for the specific case described above, if Deno gains traction. :man_shrugging:

**Comment by MartinKolarik** [comment]
My question here is, why would you use a minified version in deno instead of the original? I see no significant advantages here, and several disadvantages:
 - based on [this issue](https://github.com/denoland/deno/issues/4499), it seems deno doesn't currently handle source maps, so you stack traces will be a mess with the minified versions,
 - some packages that ship minified versions don't ship source maps, so even the support in deno wouldn't help,
 - for files minified by us, we do NOT guarantee stable hashes (there's even a message saying that in the files `Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files`. IIRC deno does something similar to SRI checks after the first fetch.

The primary use case for minification is delivering the smallest possible files in production. There, the size matters and the special comments have no meaning.

**Comment by Avaq** [comment]
> why would you use a minified version in deno instead of the original

My thinking was that Deno is much closer to Browsers than Node is. I thought that in the future, "shipping" a Deno app would just mean getting your app URL on someone's computer. The user is expected then to already have the agent (Deno) installed. If that's how it would work, I thought minification makes as much sense as it does shipping code to browsers. It's does not make a very strong case.

The more I've been thinking about it today, the less I stand behind my original proposal. That, plus the disadvantages of using minified bundles listed above, makes me think we should drop this idea.

I'll close the issue.

**Comment by MartinKolarik** [comment]
> If that's how it would work, I thought minification makes as much sense as it does shipping code to browsers...

In such a case, the types are useless though, because they are still only used during compile-time and won't catch runtime errors that depend on user input. So I think the problem here is only how to use everything unminifed during development to get compiler checks and then ship everything minified.

That is actually a more general problem - how to deal with transitive dependencies in ES imports. Right now, if you request a minified file from jsDelivr, we don't touch the imports, so the file may end up requesting other unminified files.

Once we finally get to improve our ES modules support (#18115), it is likely that when you request a minified module, we'll also rewrite all imports to minified versions. That means the original could use unminified versions everywhere and in the case you described you'd use the auto-minified version.

**Comment by Avaq** [comment]
> In such a case, the types are useless though

Very good point. If a script would've caused a compile time error on someone's user agent, the author would've shipped a broken app.
