### ISSUE TITLE
User v2ray is blacklisted.

### ISSUE THREAD

**Issue by LGTMXD** [jsdelivr/jsdelivr#18233]
_https://cdn.jsdelivr.net/gh/v2ray/v2ray-core/_

User v2ray is blacklisted.

**Comment by jimaek** [comment]
Hey, unfortunately to continue operating in China and allow Chinese developers to benefit from our global performance we have to blacklist certain projects that potentially violate Chinese policies.
But we soon plan to make changes to our logic where we blacklist this kind of projects only in China instead of globally.

Sorry about that

**Comment by MartinKolarik** [comment]
> But we soon plan to make changes to our logic where we blacklist this kind of projects only in China instead of globally.

To clarify, this will be done within a few days and after that, #18229 will follow, to make sure the rules are clear to everyone.

**Comment by MartinKolarik** [comment]
We unblocked the affected accounts in locations other than China. In China, you'll now get an error saying we can't serve it there and pointing users to the original GitHub repository.
