### ISSUE TITLE
403 Forbidden in China without Referrer

### ISSUE THREAD

**Issue by Drew233** [jsdelivr/jsdelivr#18238]
I dont konw what happened.
![image](https://user-images.githubusercontent.com/47592224/88893678-480e6480-d279-11ea-8a66-0fea11adecc8.png)

**Comment by the1812** [comment]
Same question, all files from my repo are 403 now.
![image](https://user-images.githubusercontent.com/26504152/88876326-9e69ac00-d255-11ea-920c-f0e6355619ce.png)
![image](https://user-images.githubusercontent.com/26504152/88876358-b3463f80-d255-11ea-8298-326fd2573ed6.png)

**Comment by hifocus** [comment]
It looks like jsDelivr's partner in China - Quantil, had misconfigured their CDNs. Any access without a referrer header will be returned with a 403 status code. This issue only exists in China - with Chinese IPs.

However I believe all websites that are using jsDelivr will not be affect by this incident; like mine: https://demo.qrcdn.com; since resources imported will have a referrer header.

@jimaek @MartinKolarik

**Comment by whosphp** [comment]
But any other scenes, no referrer provided. Just like tampermonkey script,  it loads js, css, and other static files without referrer.

**Comment by MartinKolarik** [comment]
As @hifocus noted, the issue seems to be related to a missing referrer header and should not - does not, based on real-time analytics - affect most of regular users/websites. We'll of course try to get this fixed asap.

**Comment by jimaek** [comment]
A fix was finally deployed. We are really sorry about the impact this had on our  Chinese users

**Comment by Drew233** [comment]
Thank you so much~

**Comment by hifocus** [comment]
thank you for maintaining the good service

**Comment by louisssliao** [comment]
awesome work
