### ISSUE TITLE
jsDelivr cannot find requested imports

### ISSUE THREAD

**Issue by DanielKehoe** [jsdelivr/jsdelivr#18298]
I'm making a comparison of module CDNs.

I have a series of test pages for module CDNs:

- https://install.guide/test/jsdelivr-pinned.html
- https://install.guide/test/jsdelivr-unpinned.html
- https://install.guide/test/jspm-importmaps.html
- https://install.guide/test/jspm-pinned.html
- https://install.guide/test/jspm-unpinned.html
- https://install.guide/test/skypack-pinned.html
- https://install.guide/test/skypack-unpinned.html

When I try jsDelivr, I get a console error: 
`
Uncaught TypeError: Failed to resolve module specifier "lit-html". Relative references must start with either "/", "./", or "../".
`

I'm using (for a pinned version):
`import { LitElement, html } from 'https://cdn.jsdelivr.net/npm/lit@2.0.0-rc.1';`
and for an unpinned version:
`import { LitElement, html } from 'https://cdn.jsdelivr.net/npm/lit';`

I'm following the import syntax I saw at https://www.jsdelivr.com/

The page loads correctly with jspm.dev or Skypack module CDNs.

How do I make jsDelivr work correctly? Am I making an error in my import syntax or is this a bug with jsDelivr?

Is this similar to the issue mentioned in  https://github.com/jsdelivr/jsdelivr/issues/18263 regarding lit-element?

**Comment by MartinKolarik** [comment]
You are using a link for a raw file, not for a module file. What you want is https://cdn.jsdelivr.net/npm/lit@2.0.0-rc.1/+esm
See https://www.jsdelivr.com/esm

**Comment by DanielKehoe** [comment]
@MartinKolarik thanks for the quick reply. I've made the correction and now I'm getting:
```
GET https://cdn.jsdelivr.net/npm/lit-html@2.0.0-rc.2/+esm net::ERR_ABORTED 404
```
for https://install.guide/test/jsdelivr-pinned.html or https://install.guide/test/jsdelivr-unpinned.html

**Comment by jimaek** [comment]
https://cdn.jsdelivr.net/npm/lit-html@2.0.0-rc.2+esm

**Comment by MartinKolarik** [comment]
> https://cdn.jsdelivr.net/npm/lit-html@2.0.0-rc.2+esm

 🤔 that link should be with a slash before `+esm`, checking.

**Comment by DanielKehoe** [comment]
`import { LitElement, html } from 'https://cdn.jsdelivr.net/npm/lit@2.0.0-rc.1+esm';`
results in
```
Uncaught TypeError: Failed to resolve module specifier "lit-html". Relative references must start with either "/", "./", or "../".
```

**Comment by DanielKehoe** [comment]
Without the slash for the unpinned version:
`import { LitElement, html } from 'https://cdn.jsdelivr.net/npm/lit+esm';`
results in
```
GET https://cdn.jsdelivr.net/npm/lit+esm net::ERR_ABORTED 404
```

**Comment by MartinKolarik** [comment]
Ok, `lit-html` v2 removed `module` field from `package.json` which is required for `/+esm` to work right now. We didn't ship support for `exports` field because the semantics for browser bundling isn't well established yet.

**Comment by DanielKehoe** [comment]
Can you handle it the way JSPM and Skypack are doing it? Or do you see problems with their approach?

I'd like to see increased reliability across the module CDNs so I can recommend using the module CDNs with web components.

**Comment by MartinKolarik** [comment]
The problems we saw previously (October 2020) when checking various approaches on the top 10k module packages:

1. Some projects have different entry points for different environments, which is, after all, the reason `exports` was created. For example, a project might have a UMD version, a CJS version, an ESM version and in some cases also variations like browser ESM and node ESM (because of some node-specific dependencies).

2. The specification doesn't really say how things should work in environments other than node. Additionally, rollup didn't implement `exports` at all (at the time) and webpack only had support for it in alpha IIRC.

3. The combination of the first two points meant that different projects used `exports` in different ways. In one project, a `browser` branch would point to an optimized ESM file, in others it might be a UMD file. In some projects, `node/import` would be a generic ESM file and `default` a CJS file, in other projects `node/import` would have node-specific code and `default` have a browser-friendly ESM file. Basically, whatever configuration we used, wouldn't work for half the projects.

I believe that this problem is less obvious with skypack and jspm because they also support CJS imports, so even if they choose the wrong file, in the end, they generate code that works most of the time.

We're planning to revisit this in the near future to support `exports` as well but those are the reasons it wasn't in the initial release.

**Comment by DanielKehoe** [comment]
Thanks for taking the time to share the detailed explanation. Looking forward to the day when it all gets sorted out :-)

**Comment by MartinKolarik** [comment]
We don't have support for `exports` yet but we did add support for `main` with `type: module` packages so this should work now: https://cdn.jsdelivr.net/npm/lit@2.0.0-rc.1/+esm

**Comment by MartinKolarik** [comment]
Exports/imports fields are now supported for all newly generated files. Files that are already cached will be refreshed soon. A testing version of our service that doesn't cache anything is also available at https://jsdelivr-origin-dev.herokuapp.com/npm/lit/+esm
