### ISSUE TITLE
Purge request & other!

### ISSUE THREAD

**Issue by MarketingPip** [jsdelivr/jsdelivr#18451]
Looking to get a purge for - [this](https://cdn.jsdelivr.net/gh/MarketingPipeline/Ace-Editor-Web-Component@1.0.0/dist/ace-editor-wc.min.js)

Deleted a release / and re-uploaded it with proper fixes. But they are not cached via CDN.

plus another question: I tried emailing Dak but still no reply! :( 

I have a repo that I am hoping I can force the files to remain cached in the main version - even after deleting them. Hoping this is possible - or I can get an exception etc..

**Comment by jimaek** [comment]
There is no way to update that file since its a static version, we cache them permanently. The correct way would be to release version 1.0.1 and use dynamic URLs like https://cdn.jsdelivr.net/gh/MarketingPipeline/Ace-Editor-Web-Component@1.0/dist/ace-editor-wc.min.js or https://cdn.jsdelivr.net/gh/MarketingPipeline/Ace-Editor-Web-Component/dist/ace-editor-wc.min.js

**Comment by MarketingPip** [comment]
😭 I have more than a few releases I messed up and I direly need to remove the cached versions. Or it will mess up the structure of the entire repo(s) when going back / using older versions - due to my mess up. 

Again is there any way we can update the urls / cached versions with the updated releases? 

As this isn't not the only repo I have made an issue for and had to delete / re-upload the releases. 

Hoping you guys can find some work around for this problem I'm facing!

**Comment by jimaek** [comment]
Based on the stats it should not have a user impact https://data.jsdelivr.com/v1/package/gh/MarketingPipeline/Ace-Editor-Web-Component/stats

I recommend to delete 1.0.0 and make a new higher and semver valid release (including the structure change) and change your docs to using a dynamic version, something like `@1` to allow people to upgrade to latest versions in the future. And if you ever need to make a breaking release you release a `@2` version.

We cache static versions permanently to protect users from things like malicious updates to old popular versions, authors deleting their repos and similar problems. Since we're production focused we want to guarantee that when a user specifies a version he will forever get the file he thinks he is getting.

**Comment by MarketingPip** [comment]
I have multiple releases messed up that don't reflect my GitHub issues. - almost ALL of releases were updated / fixed. (As I messed up version structure hardcore). 


And as well if everything is cached- why are files deleted from main branch not cached.....


Again I'm URGING / begging to request someone look at my 
code etc to verify no malicious changes etc. So I can update the CDN files to reflect the releases.

Again please I'm begging - example I messed up https://github.com/MarketingPipeline/Markdown-Tag 

Literally ALL the releases I need to delete (on GitHub) then have them re-cached. 


If I'm forced to take the options you provided me - I'll just further mess up the repo(s) structures..

**Comment by jimaek** [comment]
We're looking into it

**Comment by MarketingPip** [comment]
@jimaek - well dang :sob: 

Maybe I could get this as a feature request for Christmas. With an indication to users it was purged etc > and old purged packages / releases go to another route possibly...? Just an idea!

Also - regarding the caching. I am hoping / needing a file(s) to be cached for sure. I went to move them into another folder in the main directory. But they do NOT cache. (which I am wanting them to be cached regardless if I delete them). As the CDN has done this for other repos I have deleted / made private even after deleting files etc.. But not for my public repo [here](https://github.com/MarketingPipeline/Markdown-Tag)

**Comment by jimaek** [comment]
>Maybe I could get this as a feature request for Christmas. With an indication to users it was purged etc > and old purged packages / releases go to another route possibly...? Just an idea!

The files are stored permanently in our S3 bucket after the first request, the whole system relies on this. So its not a feature we can build unfortunately. In the far future we may find a way to make it more dynamic. But it would be a large project.

>Also - regarding the caching. I am hoping / needing a file(s) to be cached for sure. I went to move them into another folder in the main directory. But they do NOT cache. (which I am wanting them to be cached regardless if I delete them). As the CDN has done this for other repos I have deleted / made private even after deleting files etc.. But not for my public repo [here](https://github.com/MarketingPipeline/Markdown-Tag)

I dont understand, what exactly is not caching? Do you have example URLs with details about what is wrong?

**Comment by MartinKolarik** [comment]
Most likely - the permanent storage is not used if you request `@branch` instead of `@tag`

**Comment by MarketingPip** [comment]
So the main files in the Markdown Tag repo. When I move them. They do not cache under main (and message occurs saying you can't find file). 

When I have had it before - where I have DELETED the repo & files inside and even made it private (and JSDeliver cached the files - notta clue how but lol). I'm hoping that this can be FORCED to happen with these 3 files (with commit messages - Moved back to main).

I'm hoping they cache so I don't mess up and users who are currently using the scripts in the main - when I move them to another area.
