### ISSUE TITLE
Failed to bundle @pixi/color@7.2.0-beta/+esm

### ISSUE THREAD

**Issue by SuperSodaSea** [jsdelivr/jsdelivr#18469]
**Describe the bug**

Ref pixijs/pixijs#9189.

jsDelivr failed to bundle `@pixi/color@7.2.0-beta/+esm`, see the link below.

**Affected jsDelivr links**

<https://cdn.jsdelivr.net/npm/@pixi/color@7.2.0-beta/+esm>

**Response headers**

N/A. This should have nothing to do with the issue.

**Screenshots**

```
/**
 * Failed to bundle using Rollup v2.74.1.
 * If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr
 */

 throw new Error('Failed to bundle using Rollup v2.74.1. If you believe this to be an issue with jsDelivr, and not with the package itself, please open an issue at https://github.com/jsdelivr/jsdelivr');
```

**Please complete the following information:**

 - Device OS: Windows 10
 - Browser: Chrome
 - Browser version: 110
 - VPN provider if you use one: N/A
 - Your location (country): China

**Additional context**

Skypack works well with this package: <https://cdn.skypack.dev/@pixi/color@7.2.0-beta>. There is no detailed error information on jsDelivr, so I don't know what's going on.

**Comment by MartinKolarik** [comment]
Hey, thanks for the report. The error comes from rollup, specifically from its source map processing. It seems to be caused by the `null` within `sources` in https://cdn.jsdelivr.net/npm/@pixi/color@7.2.0-beta/lib/Color.mjs.map.

After briefly checking https://sourcemaps.info/spec.html I think the `null` value is not allowed there. It can be used in `sourcesContent` to indicate the source content is not available but its name must be present.

**Comment by SuperSodaSea** [comment]
@MartinKolarik Thanks for the information about the invalid source map! There should be some problems in our release process, I will deal with them.
