### ISSUE TITLE
Asia representation

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/jsdelivr#2272]
@ping @as-com @watermelonjuice Hey guys, as far as I know you have connections with Asia. 
Either are located there or know one of the languages.
I was wondering if you would be interested to take a more active role at jsDelivr.

This would involve:
* Getting Asian companies to sponsor us. (CDNs or servers)
* Do benchmarks to improve our [load balancing code](https://github.com/jsdelivr/dns-openmix)
* Get in contact with Asian open source projects for potential partnerships 
* General promotion of jsDelivr in Asian countries. Maybe even a translation of our website?
For example there is no point for http://jsdelivr.cn/ to exist.

You would be our official representation and could help us a lot.

What do you think? Is there any interest in this?

**Comment by jimaek** [comment]
Can someone contact this website http://jsdelivr.cn/ and ask them to either shut it down or at least use cdn.jsdelivr.net as the CDN instead of delivr.cdnjs.net (not owned by by cdnjs.com)? 
They didn't steal only the name but the design too. 

I can send a DMCA takedown to Linode where they seem to be hosted but I guess they will simple change the provider.

**Comment by Yexiaoxing** [comment]
Finding the owner of jsdelivr.cn and cdnjs.net..

**Comment by Yexiaoxing** [comment]
Jsdelivr.cn has closed.

**Comment by jimaek** [comment]
Wow nice, how did you do it? Tell us your story :)

Thank you!

**Comment by vigneshshanmugam** [comment]
I am a Web Developer focussing on Web Performance from India and would like to help on testing benchmarks of DNS load balancing algorithm. I am also in contact with Cedexis team on helping with the radar solution.

**Comment by jimaek** [comment]
@vigneshshanmugam Check out these 2 projects https://github.com/jsdelivr/dns-openmix https://github.com/jsdelivr/vps-rum and see if you can help with anything

**Comment by MidnightWonderer** [comment]
Thai here.
My country is a bit exotic and not well known in someplace. And have very limited international bandwidth.
I don't like the idea of being "official representation" because it sound serious.

However, I'm here to tell you that you can ask me for help.
Weather it's about language, VPS/Server sourcing (I don't think you will get good sponsored one easily though.), You want to contact Thai company on your behalf but want me to translate something for you. You wanted to know what message in Thai website you saw is about or want me to find more info about some company or service for example. (Google translate is not so helpful) Or want me to inquire for something by phone.

Ask me anytime. (I just not guarantee that I will be available anytime.)

**Comment by pnommensen** [comment]
thanks @MidnightWonderer :) :+1:

**Comment by jimaek** [comment]
Who wants to test the following Chinese CDNs?
http://e4a460fff0.a.uxengine.net/r20.gif
http://90f29d9537a6c39a.tan14.net/r20.gif

Not sure if it makes sense to use them both. Which one is the fastest?

**Comment by as-com** [comment]
@jimaek Do you have the main websites of those CDNs? I just want to see their network maps/peerings.

**Comment by jimaek** [comment]
http://tan14.cn/ https://manage.c3edge.com/about
