### ISSUE TITLE
Remove query strings from static resources

### ISSUE THREAD

**Issue by soodaa** [jsdelivr/jsdelivr#5249]
I run a test with http://gtmetrix.com to measure the load time of my website https://www.internetvergelijk.nl
They recommend to remove query strings from static resources:

"Resources with a "?" in the URL are not cached by some proxy caching servers. Remove the query string and encode the parameters into the URL for the following resources: https://cdn.jsdelivr.net/g/conditionizr@4.5.0,modernizr@2.6.2,jquery@2.1.4?ver=4.2.2"

I use the following code: https://cdn.jsdelivr.net/g/conditionizr@4.5.0,modernizr@2.6.2,jquery@2.1.4
Is it possible to get a higher score when using the combining functionality?

**Comment by jimaek** [comment]
Its not jsDelivr that is adding the `?ver=4.2.2"` part but your website. So you need to change your WordPress settings to remove it. 
Its not a jsDelivr problem but a WordPress problem

**Comment by soodaa** [comment]
Thanks a lot, i will look it up.

**Comment by hubdotcom** [comment]
In order to prevent your enqueued scripts and style in WordPress to use a version number, all you need to do is use null value in the $ver parameter. Given below is how you’ll implement it in the WordPress enqueue functions:

<?php wp_register_script('basic', plugins_url('js/basic.js', __FILE__), array(), null, true); >

http://wpcrux.com/wordpress-enqueue-functions-version/
