### ISSUE TITLE
Use Zopfli for compression

### ISSUE THREAD

**Issue by Daniel15** [jsdelivr/jsdelivr#7928]
See http://minime.stephan-brumme.com/:

> Surprisingly, most Content Delivery Networks (CDNs) give you a quite bad level of GZIP compression.

> Google's Zopfli (open source) is currently the best GZIP compressor and produces the smallest files.
It produces files fully compatible to the DEFLATE algorithm (used by GZIP) but in order to find even better compression

As an example, D3 on JSDelivr is 53410 bytes, whereas a version compressed with Zopfli is only 51278 bytes (see http://minime.stephan-brumme.com/d3/3.5.8).

I'm not sure how you compress the files, but I assume they're compressed ahead of time rather than dynamically compressing them for every single request (which would use more CPU than necessary). I don't know a lot about Zopfli, but this might be as simple as changing the way you compress the files when loading them onto the CDN.

**Comment by jimaek** [comment]
Most of our CDN providers re-compress the files on-the-fly regardless of what the origin serves. So we have 0 control over the final compression that the user gets. Unless the CDNs enable this feature we cant support it.

**Comment by Daniel15** [comment]
Interesting... Why do they re-compress? That seems like a waste of CPU cycles given it's the same files that keep getting served :disappointed:

**Comment by jimaek** [comment]
Not sure why, it could be a technical limitation. From what I've seen they all have different Gzip compression levels and even if I set level 9 on the origin they will re-compress to their own levels.
So no way to implement Zopfli

**Comment by tomByrer** [comment]
I'm an optimization geek myself Daniel, but I think the best compression can only save a few HTTP packets at best if the JS is minified.  Could make up one of those extra packets if you [collate scripts](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request).

If you're good with Docker & Pearl, I could use help with minifing fonts though ;)

**Comment by stbrumme** [comment]
Hi, my name is Stephan Brumme and I made the website Daniel mentioned.
Compression on-the-fly is a waste of CPU power but given that modern computers can gzip more than 100 MByte/s a viable way. That could explain the low level of compression observed => even faster speed.
The problem with pre-compressed files is that some older clients don't support gzip/deflate compression (I would say less than 1%). Therefore you could either:
A) store the original file and compress on-the-fly or
B) store the compressed and decompress on-the-fly.
The former is easier to set up and to maintain - clearly at the cost of wasting CPU power.
Btw, I think the biggest strength of CDNs is that often you don't need to download the scripts at all because they are already cached on your local computer. Therefore merging jQuery with your website-specific scripts will usually improve compression level but then there is no "sharing" of jQuery with other websites. And there are plenty ...

**Comment by tomByrer** [comment]
Thanks for your feedback @stbrumme; I didn't consider non-gzip compatible clients.

I think 'hitting the cache lottery' is bit of a myth; very rare since there are so many hard-coded versions.
https://github.com/h5bp/html5-boilerplate/pull/1327#issuecomment-14857390

**Comment by jimaek** [comment]
Closing since its not possible for us to enable Zopfli :(
