### ISSUE TITLE
algoliasearch 3.12.0 not on CDN

### ISSUE THREAD

**Issue by vvo** [jsdelivr/jsdelivr#9800]
present in github: https://github.com/jsdelivr/jsdelivr/tree/master/files/algoliasearch/3.12.0
But no trace on CDN

Did we forgot something?

**Comment by jimaek** [comment]
deployhq.com was having problems during that time, they fixed it since. I did a deploy of everything they missed but I guess unfortunately algolia slipped.
If this happens again I will do a few changes to the infrastructure to avoid this kind of issues.
Sorry about that.

Btw we are working on v2 of our API here https://github.com/jsdelivr/api/tree/v2
Check it out and let me know if you have any feedback!

**Comment by jimaek** [comment]
Just to make it clear. The files were never uploaded to the CDN, so there was no user impact or anything of sorts.

**Comment by vvo** [comment]
Yes the only user impact being misunderstanding on why the file is not in the CDN
